name: CI

on:
  pull_request:
    branches: 
  push:
    branches: 

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Hardhat tests
        env:
          PRIVATE_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
          BASE_SEPOLIA_RPC: "https://sepolia.base.org"
          COINMARKETCAP_API_KEY: ""
        run: npx hardhat test

      - name: Install Slither
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install slither-analyzer

      - name: Run Slither security scan
        run: slither. --filter-paths "node_modules,contracts/test,contracts/mocks" --exclude-informational --exclude-low
        continue-on-error: true
